//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancosMDacosta
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BancoUsers
    {   
        [Key]
        public int IdBancoUser { get; set; }
        [Required(ErrorMessage = "Login requerido")]
        [StringLength(10)]
        public string Login { get; set; }
        [StringLength(10)]
        [Required(ErrorMessage = "Contraseña requerido")]
        public string Password { get; set; }
        public string Grupos { get; set; }
    }
}
