//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancosMDacosta
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Cuentas
    {
        [Key]
        public int IdCuenta { get; set; }
        [ForeignKey("Clientes")]
        public int IdCliente { get; set; }
        [ForeignKey("Entidades")]
        public int IdEntidad { get; set; }
        [Required(ErrorMessage = "El Número de Cuenta es obligatorio")]
        [StringLength(20, ErrorMessage = "El Número de Cuenta no puede superar {1} caracteres")]
        public string NumCuenta { get; set; }
        [Required(ErrorMessage = "La Fecha de Apertura es obligatoria")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FechaApertura { get; set; }
        [ForeignKey("TiposCuenta")]
        public Nullable<int> IdTipoCuenta { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "El saldo ha de ser mayor que {1}")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> Saldo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual TiposCuenta TiposCuenta { get; set; }
    }
}
