//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancosMDacosta
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Operaciones
    {
        [Key]
        public int IdOperacion { get; set; }
        [Required]
        [ForeignKey("Clientes")]
        public int IdCliente { get; set; }
        [Required]
        public int Tipo { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
